Repository ResidenciaTICBrisa/T2G7-Revista-Darcy, pull requests merged in 2024-08, with the labels that each got.

#155 :books: ata da reuniao 18 com a SECOM
  docs/atas/equipe_cliente/ata18.md
  mkdocs.yml
Labels: documentation

#165 :books: fim da documentacao das sprints
  docs/requisitos/visao_de_projeto.md
  docs/sprints/sprint12/planejamento.md
  docs/sprints/sprint12/resultados.md
Labels: documentation

#166 Landing page e documento Dossie
  docs/assets/DARCY_28_miniatura.png
  docs/landingPage/landingPage.html
  docs/release/dossie.md
  mkdocs.yml
Labels: documentation, enhancement

#168 Ajustes de usabilidade finais e correção pré-release 4
  docs/assets/DARCY_28_miniatura.png
  docs/landingPage/landingPage.html
  docs/release/dossie.md
  mkdocs.yml
Labels: bug, documentation, enhancement
